# This file was generated by GoReleaser. DO NOT EDIT.
cask "aicof" do
  name "aicof"
  desc "CLI for managing the AICoF (Artificial Intelligence Coding Framework)"
  homepage "https://github.com/ar4mirez/aicof"
  version "1.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aicof"

  on_macos do
    on_intel do
      url "https://github.com/ar4mirez/aicof/releases/download/v#{version}/aicof_#{version}_darwin_amd64.tar.gz"
      sha256 "ef1cc68dffb76c48029cd9d7b3e1b7b026e4f74e0d3f905e871a4696c39fb44b"
    end
    on_arm do
      url "https://github.com/ar4mirez/aicof/releases/download/v#{version}/aicof_#{version}_darwin_arm64.tar.gz"
      sha256 "852f29872b56cd1b4e795da257e6b9df95c4fd6edd4e66e942f5eade1f599838"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ar4mirez/aicof/releases/download/v#{version}/aicof_#{version}_linux_amd64.tar.gz"
      sha256 "2ee8b9cbace896a87a61a89c18841c8224df20da1953bbf2715a97d690bbb164"
    end
    on_arm do
      url "https://github.com/ar4mirez/aicof/releases/download/v#{version}/aicof_#{version}_linux_arm64.tar.gz"
      sha256 "7cddc12bb2246c9073aa67a89b43ad8788cad1042a9a04437e310c565a6bb01a"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aicof"]
    end
  end

  # No zap stanza required
end
