# This file was generated by GoReleaser. DO NOT EDIT.
cask "aicof" do
  name "aicof"
  desc "CLI for managing the AICoF (Artificial Intelligence Coding Framework)"
  homepage "https://github.com/ar4mirez/aicof"
  version "1.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aicof"

  on_macos do
    on_intel do
      url "https://github.com/ar4mirez/aicof/releases/download/v#{version}/aicof_#{version}_darwin_amd64.tar.gz"
      sha256 "3d88a2ec2955994eebf936bb1013aa1d6d28de4ce6fff2ca8c5015999805c5f0"
    end
    on_arm do
      url "https://github.com/ar4mirez/aicof/releases/download/v#{version}/aicof_#{version}_darwin_arm64.tar.gz"
      sha256 "0ef17537540dcc80049065efd77dfca8d330bf95e8a716e4b2cc8aa185e1b2eb"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ar4mirez/aicof/releases/download/v#{version}/aicof_#{version}_linux_amd64.tar.gz"
      sha256 "bbc8a5e98d2749602ce7373386a54e99d7c35803b3aacaaa6028a31f595c9d47"
    end
    on_arm do
      url "https://github.com/ar4mirez/aicof/releases/download/v#{version}/aicof_#{version}_linux_arm64.tar.gz"
      sha256 "2137516111d5373f405709c029caec28835cc73bbbc80872d1970c65707ddbab"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aicof"]
    end
  end

  # No zap stanza required
end
