# This file was generated by GoReleaser. DO NOT EDIT.
cask "berth" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/berth"], must_succeed: false
    end
  end

  version "0.8.0"

  on_macos do
    on_arm do
      sha256 "b62d7ef1c0e4ed611df1a42f849e798a7382f5bb5608a4b6469bff0ab5bb64a9"
      url "https://github.com/ar4mirez/berth/releases/download/v#{version}/berth_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "6b57a897f65a7371bdd0360c360abf4ac988f944dfda748db65db2351b0432d0"
      url "https://github.com/ar4mirez/berth/releases/download/v#{version}/berth_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a1db0c342dc912344e3753f5f52bf0aee929b378515685a04c12f9b5006a37e6"
      url "https://github.com/ar4mirez/berth/releases/download/v#{version}/berth_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a9087720f59d016be490f626f8d1daeeca63ff986fddae4ab00f3533955f9c5b"
      url "https://github.com/ar4mirez/berth/releases/download/v#{version}/berth_#{version}_linux_amd64.tar.gz"
    end
  end

  name "berth"
  desc "Isolated Claude Code environments, one per organization"
  homepage "https://ar4mirez.github.io/berth/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "berth"
  manpage "man/berth.1"
  bash_completion "completions/berth.bash"
  fish_completion "completions/berth.fish"
  zsh_completion "completions/_berth"

  # No zap stanza required
end
