# This file was generated by GoReleaser. DO NOT EDIT.
cask "berth" do
  version "0.4.1"

  on_macos do
    on_arm do
      sha256 "0f8327cece124cdf3ce6f383837a0261092c804c0e947ee73f0883eab2d82c8d"
      url "https://github.com/ar4mirez/berth/releases/download/v#{version}/berth_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "330621c4976f5f0f59d036cf386424a0832024cd2ab65954ee67ee07cac7ec27"
      url "https://github.com/ar4mirez/berth/releases/download/v#{version}/berth_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "976865bc08bd4a956b893f9b38202c08c3a2639a19258127a07479fa2c43f927"
      url "https://github.com/ar4mirez/berth/releases/download/v#{version}/berth_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b251d6ff5a3a2f91fd34e717222b2ca91af15d0bf95234f645cb1832efaac673"
      url "https://github.com/ar4mirez/berth/releases/download/v#{version}/berth_#{version}_linux_amd64.tar.gz"
    end
  end

  name "berth"
  desc "Isolated Claude Code environments, one per organization"
  homepage "https://ar4mirez.github.io/berth/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "berth"
  manpage "man/berth.1"
  bash_completion "completions/berth.bash"
  fish_completion "completions/berth.fish"
  zsh_completion "completions/_berth"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/berth"]
    end
  end

  # No zap stanza required
end
