# This file was generated by GoReleaser. DO NOT EDIT.
cask "berth" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/berth"], must_succeed: false
    end
  end

  version "0.8.1"

  on_macos do
    on_arm do
      sha256 "fae829f55813d266b981eca71de4d01ac800f6d5478ba2da315206cb760819d4"
      url "https://github.com/ar4mirez/berth/releases/download/v#{version}/berth_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "401f29ef06af6757a9b5378dfb0209ee4b3dd92bac5840073f639512c439608f"
      url "https://github.com/ar4mirez/berth/releases/download/v#{version}/berth_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "7dda1addda54bd4d798b162b2ee16b5625facb13424004940e18a8e3646ed9d0"
      url "https://github.com/ar4mirez/berth/releases/download/v#{version}/berth_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "76f2ae7dfc2dcb21d5316cc68d02080775f8972f039a5449062be5acfad29b6c"
      url "https://github.com/ar4mirez/berth/releases/download/v#{version}/berth_#{version}_linux_amd64.tar.gz"
    end
  end

  name "berth"
  desc "Isolated Claude Code environments, one per organization"
  homepage "https://ar4mirez.github.io/berth/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "berth"
  manpage "man/berth.1"
  bash_completion "completions/berth.bash"
  fish_completion "completions/berth.fish"
  zsh_completion "completions/_berth"

  # No zap stanza required
end
