# This file was generated by GoReleaser. DO NOT EDIT.
cask "samuel" do
  version "2.4.0-rc.2"

  on_macos do
    on_intel do
      sha256 "6c22e6e4f7c70e89c43d00e3992d7c704e795885100caa5f5cc8d6899a109bdc"
      url "https://github.com/samuelpkg/samuel/releases/download/v#{version}/samuel_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1041e658f6a31311f01a0a0f6a482cfb27020d1f9787500f7f59eb815d646f99"
      url "https://github.com/samuelpkg/samuel/releases/download/v#{version}/samuel_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6f107f259c170715b7fe625177b5ec35d56a59794194a5361fb4c066801c184b"
      url "https://github.com/samuelpkg/samuel/releases/download/v#{version}/samuel_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "611fea9d23b878b5e781d0954aa8146f2ed954131f96290c57b686d594ef6b27"
      url "https://github.com/samuelpkg/samuel/releases/download/v#{version}/samuel_#{version}_linux_arm64.tar.gz"
    end
  end

  name "samuel"
  desc "Rails for AI coding assistants"
  homepage "https://samuelpkg.github.io/samuel/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "samuel"
  bash_completion "completions/samuel.bash"
  fish_completion "completions/samuel.fish"
  zsh_completion "completions/samuel.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/samuel"]
    end
  end

  # No zap stanza required

end
