# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Samuel < Formula
  desc "Rails for AI coding assistants"
  homepage "https://samuelpkg.github.io/samuel/"
  version "2.0.0-rc.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/samuelpkg/samuel/releases/download/v2.0.0-rc.8/samuel_2.0.0-rc.8_darwin_amd64.tar.gz"
      sha256 "e9e423c272f18124d85ba0c324cc87942335dd022e77eb50da083c12d3448fa0"

      define_method(:install) do
        bin.install "samuel"
        generate_completions_from_executable(bin/"samuel", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/samuelpkg/samuel/releases/download/v2.0.0-rc.8/samuel_2.0.0-rc.8_darwin_arm64.tar.gz"
      sha256 "1e9989020bec653cfd799c0ca63be5f6a146425d9077d1d8559b1dfb68b0e345"

      define_method(:install) do
        bin.install "samuel"
        generate_completions_from_executable(bin/"samuel", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/samuelpkg/samuel/releases/download/v2.0.0-rc.8/samuel_2.0.0-rc.8_linux_amd64.tar.gz"
      sha256 "19107f2e84ca72e657f147c495b6561d27d1580ff6aae8fd3ee629ff86346f44"
      define_method(:install) do
        bin.install "samuel"
        generate_completions_from_executable(bin/"samuel", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/samuelpkg/samuel/releases/download/v2.0.0-rc.8/samuel_2.0.0-rc.8_linux_arm64.tar.gz"
      sha256 "9dfecb41bdf87018abeef43792a231bf29cc9eb31f98bd6e9b9541ae2eb232b0"
      define_method(:install) do
        bin.install "samuel"
        generate_completions_from_executable(bin/"samuel", "completion")
      end
    end
  end

  test do
    system "#{bin}/samuel", "version"
  end
end
